### ISSUE TITLE
Button "CU-Inventur" liefert falsche Kanalanzahl

### ISSUE THREAD

**Issue by Herbert-Testmann** [jens-maus/scriptparser#1]
Version 1.5
Button "CCU-Inventur"
Ergebnis:   6 Kanäle in 180 Geräten

richtig wäre:  594 Kanäle in 179 Geräten

Die 6 Kanäle könnten aus dem 180ten Gerät kommen.  Das würde bedeuten, es wird nicht summiert, oder die falsche variable ausgegeben.

**Comment by litti** [comment]
Vielen Dank für den Hinweis. In Version 1.7 ist das Problem behoben.
