### ISSUE TITLE
Anzahl der Summe der Kanäle in 1.7  falsch

### ISSUE THREAD

**Issue by Herbert-Testmann** [jens-maus/scriptparser#3]
Die Anzahl der Kanäle in der Summe ist leider immer noch falsch.

6 KanÃ¤le in 180 GerÃ¤ten:

**Comment by litti** [comment]
Das kann ich hier leider nicht nachvollziehen. Bitte leere einmal den Browser-Cache und probiere es noch einmal.

**Comment by Herbert-Testmann** [comment]
Nach Verwendung eines anderen Browsers auf einem anderen PC sieht auch die GUI der V1.7 komplett anders aus. Erkennbar an der Titelzeile mit Version und Hinweistext.

Damit ist die Anzahl der Kanäle richtig.

Sorry, Fehler lag bei mir.
